GET http://localhost:8000/api/access
Content-Type: application/json

{
    "count": 10,
    "page": 1
}

###

GET http://localhost:8000/api/access/count

###

GET http://localhost:8000/api/access/1

###

GET http://localhost:8000/api/access/document/2
Content-Type: application/json

{
    "count": 10,
    "page": 1
}

###

GET http://localhost:8000/api/access/document/2/count

###
