GET http://localhost:8000/api/access
Content-Type: application/json

{
    "count": 10,
    "page": 1
}

###

GET http://localhost:8000/api/access/count

###

GET http://localhost:8000/api/access/10

###

GET http://localhost:8000/api/access/document/1
Content-Type: application/json

{
    "count": 10,
    "page": 1
}

###

GET http://localhost:8000/api/access/document/2/count

###

POST http://localhost:8000/api/access/add
Content-Type: application/json

{
    "usernameUser": "user3",
    "idDocument": 3
}

###

DELETE http://localhost:8000/api/access/remove/2

###
