GET http://localhost:8000/api/user
Content-Type: application/json

{
    "count": 10,
    "page": 1
}

###

GET http://localhost:8000/api/user/count

###

GET  http://localhost:8000/api/user/1

###

POST http://localhost:8000/api/user/add
Content-Type: application/json

{
    "name": "user4",
    "username": "user4",
    "email": "user4@gmail.com",
    "password": "12345678",
    "role": "user",
    "is_active": true
}

###

PUT http://localhost:8000/api/user/change/7
Content-Type: application/json

{
    "name": "Rizky Irswanda Ramadhana",
    "username": "rz_irswanda",
    "email": "rizky.irswanda115@gmail.com",
    "role": "user"
}

###


PUT http://localhost:8000/api/user/change-password/7
Content-Type: application/json

{
    "password": "10102005"
}

###


PUT http://localhost:8000/api/user/change-active/7

###

DELETE http://localhost:8000/api/user/remove/7

###